management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
app:
  jwt:
    secret: ${JWT_SECRET:xjPc1RLUXukJgO9yI1ryhVa1YY3msah9pig5sWBn1pi}
    jwtCookieName: jwt-access

