eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
spring:
  application:
    name: orders
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true

spring.cloud.openfeign.circuitbreaker.enabled: true

resilience4j.circuitbreaker:
  instances:
    products:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50