eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
server:
  port: 8081
spring:
  application:
    name: order
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/orders
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true

spring.cloud.openfeign.circuitbreaker.enabled: true

resilience4j.circuitbreaker:
  instances:
    products:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      failureRateThreshold: 50

app:
  jwt:
    secret: ${JWT_SECRET:xjPc1RLUXukJgO9yI1ryhVa1YY3msah9pig5sWBn1pi}
    jwtExpirationMs: 900000 # 15 minutes
    jwtRefreshExpirationMs: 604800000 # 7 days
    jwtCookieName: jwt-access
    jwtRefreshCookieName: jwt-refresh
