eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
spring:
  application:
    name: users
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
management:
  tracing:
    sampling:
      probability: 1.0
app:
  jwt:
    secret: ${JWT_SECRET:xjPc1RLUXukJgO9yI1ryhVa1YY3msah9pig5sWBn1pi}
    jwtExpirationMs: 900000 # 15 minutes
    jwtRefreshExpirationMs: 604800000 # 7 days
    jwtCookieName: jwt-access
    jwtRefreshCookieName: jwt-refresh